INSERT INTO "PUBLIC"."SETTING" VALUES('from', 'Afzender van mails', 'ccnl.mail', 'ledenadministratie@citroenclubnederland.nl', 'ccnl.mail.from');           
INSERT INTO "PUBLIC"."SETTING" VALUES('subject', '', 'ccnl.mail', STRINGDECODE('Opzegging lidmaatschap Citro\u00ebn Club Nederland'), 'ccnl.mail.subject'); 
INSERT INTO "PUBLIC"."SETTING" VALUES('host', '', 'spring.mail', 'server60.hosting2go.nl', 'spring.mail.host');               
INSERT INTO "PUBLIC"."SETTING" VALUES('port', '', 'spring.mail', '587', 'spring.mail.port');  
INSERT INTO "PUBLIC"."SETTING" VALUES('username', '', 'spring.mail', 'ledenadministratie@citroenclubnederland.nl', 'spring.mail.username');   
INSERT INTO "PUBLIC"."SETTING" VALUES('password', '', 'spring.mail', '**********', 'spring.mail.password');  
INSERT INTO "PUBLIC"."SETTING" VALUES('mail.smtp.starttls.enable', '', 'spring.mail.properties', 'true', 'spring.mail.properties.mail.smtp.starttls.enable'); 
INSERT INTO "PUBLIC"."SETTING" VALUES('mail.smtp.auth', '', 'spring.mail.properties', 'true', 'spring.mail.properties.mail.smtp.auth');       
INSERT INTO "PUBLIC"."SETTING" VALUES('number', 'Volgnummer clubblad', 'ccnl.magazine', '366', 'ccnl.magazine.number');       
INSERT INTO "PUBLIC"."SETTING" VALUES('db', 'Database Backup-/Restore directory', 'ccnl.directory', 'C:/temp', 'ccnl.directory.db');          
INSERT INTO "PUBLIC"."SETTING" VALUES('sepa', 'Basis directory voor SEPA formulieren', 'ccnl.directory', 'C:/Users/SKIKK/OneDrive/prive/CCNL_prive/ledenadministratie', 'ccnl.directory.sepa');               
INSERT INTO "PUBLIC"."SETTING" VALUES('excel', 'Directory voor Excel import en export', 'ccnl.directory', 'C:/temp', 'ccnl.directory.excel'); 
INSERT INTO "PUBLIC"."SETTING" VALUES('magazine', 'Directory voor adresbestanden van het clubblad', 'ccnl.directory', 'C:/temp', 'ccnl.directory.magazine');  