package nl.ealse.ccnl.control.menu;

/**
 * A MenuChoice for every choice made in the application's menu.
 * 
 * @author ealse
 *
 */
public enum MenuChoice {
  NEW_MEMBER, AMEND_MEMBER, CANCEL_MEMBERSHIP, PAYMENT_AUTHORIZATION, ADD_IBAN_NUMBER,
  //
  NEW_PARTNER, AMEND_PARTNER, DELETE_PARTNER,
  //
  NEW_EXTERNAL_CLUB, AMEND_EXTERNAL_CLUB, DELETE_EXTERNAL_CLUB,
  //
  NEW_EXTERNAL_RELATION, AMEND_EXTERNAL_RELATION, DELETE_EXTERNAL_RELATION,
  //
  NEW_INTERNAL_RELATION, AMEND_INTERNAL_RELATION, DELETE_INTERNAL_RELATION,
  //
  MAGAZINE_ADDRESS_LIST, CARD_ADDRESS_LIST, MAGAZINE_INVALID_ADDRESS,
  //
  ADD_DOCUMENT, VIEW_DOCUMENT, DELETE_DOCUMENT,
  //
  REPORT_ALL_DATA, REPORT_NEW_MEMBERS, REPORT_OVERDUE_MEMBERS, REPORT_CANCELLED_MEMBERS, REPORT_ARCHIVE,
  //
  RESET_PAYMENTS, ANNUAL_ROLLOVER, PRODUCE_DIRECT_DEBITS_FILE,
  //
  PRODUCE_REMINDER_LETTERS_DD, PRODUCE_REMINDER_LETTERS_BT,
  //
  RECONCILE_PAYMENTS, HANDLE_OVERDUE,
  //
  MANAGE_SEPA_FORM, TEMPLATES_OVERVIEW,

  MANAGE_BACKUP_DATABASE, MANAGE_RESTORE_DATABASE,

  IMPORT_FROM_EXCEL,

  SETTINGS, MANAGE_ARCHIVE;

}
